### ISSUE TITLE
Матрица залита

### ISSUE THREAD

**Issue by WrongBit** [GyverLibs/GyverMAX7219#1]
Я подключил MAX7219 (4x1 матрицы) к Mega328P так:
VCC/GND => 5V / GND
CS => 10
DIN => 11
CLK => 8
(это всё цифровые пины) Номера пинов взял здесь: https://protosupplies.com/wp-content/uploads/2017/12/Arduino-Nano-Board-Pinout-2.jpg (красные).
И когда залил прошивку:

```
void setup()
{
    mtrx.begin();
    mtrx.setBright(1);
    mtrx.clear();
}

```
... матрица просто ВСЯ зажглась, причём ярко (т.е. это явно не яркость=1). Что тут может быть, помогите пожалуйста.
Пробовал выводить точку, линию - бестолку, просто горят все LED'ы.

**Comment by GyverLibs** [comment]
Номера пинов написаны на плате. Подключать нужно:
- Либо к аппаратному SPI (CLK 13, DAT 11), CS на любой пин и его указать `MAX7219 < W, H, CS> mtrx;`
- Либо на любые пины и все их указать `MAX7219 < W, H, CS, DATA, CLK > mtrx`
