### ISSUE TITLE
7-сегментный модуль на MAX7219

### ISSUE THREAD

**Issue by khusamov** [GyverLibs/GyverMAX7219#2]
Привет!
Спасибо за библиотеку!
Вопрос: Почему библиотека не поддерживает 7-сегментный модуль на MAX7219?

**Comment by GyverLibs** [comment]
Привет, библиотека в разработке, планируется поддержка всех 7 сегментных модулей. Но не знаю когда, автор мой коллега, он пока в отъезде)

**Comment by GyverLibs** [comment]
Привет, потому что это библиотека для матрицы, а не для 7 сегментного модуля
